FROM oraclelinux:8-slim

MAINTAINER Cloorc <wittcnezh@foxmail.com>

RUN microdnf install oracle-instantclient-release-el8 && \
    microdnf install oracle-instantclient-basic && \
    microdnf clean all

